import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import GoogleTag from "@/utils/GoogleTag";
import MetaPixel from "@/utils/MetaPixel";
import ChannelTalk from "@/utils/ChannelTalk";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="space-y-12 mx-auto 
        max-w-7xl px-4 py-24 sm:px-6 sm:py-32 lg:px-8"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center justify-center mx-auto max-w-4xl">
          <GoogleTag />
          <MetaPixel />
          <ChannelTalk />
          {children}
        </div>
      </body>
    </html>
  );
}
